import type { Metadata } from 'next'
import { Geologica } from 'next/font/google'
import { getClient } from '@faustwp/experimental-app-router'
import { gql } from '@apollo/client'
import { Header } from '@/components/Header'
import { FaustProvider } from '@faustwp/experimental-app-router/ssr'
import './globals.css'
import '@/faust.config.js'
import Link from 'next/link'

const googleFont = Geologica({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const client = await getClient()

  const { data } = await client.query({
    query: gql`
      query GetLayout {
        generalSettings {
          title
          description
        }
        primaryMenuItems: menuItems(where: { location: PRIMARY }) {
          nodes {
            id
            label
            uri
            parentId
          }
        }
        footerMenuItems: menuItems(where: { location: FOOTER }) {
          nodes {
            id
            label
            uri
          }
        }
      }
    `,
  })

  console.log(data.primaryMenuItems)
  return (
    <html lang="en">
      <body className={googleFont.className}>
        <FaustProvider>
          <div className="flex flex-col min-h-[100dvh]">
            <Header menuItems={data.primaryMenuItems} />

            {children}
            <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
              <p className="text-xs text-gray-500 dark:text-gray-400">
                © {new Date().getFullYear()} Spazio Bizzarro. All rights reserved.
              </p>
              <nav className="sm:ml-auto flex gap-4 sm:gap-6">
                <Link className="text-xs hover:underline underline-offset-4" href="#">
                  Amministrazione trasparente
                </Link>
                <Link className="text-xs hover:underline underline-offset-4" href="#">
                  Privacy
                </Link>
              </nav>
            </footer>
          </div>
        </FaustProvider>
      </body>
    </html>
  )
}
