import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getClient } from '@faustwp/experimental-app-router'
import { gql } from '@apollo/client'
import { Header } from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const client = await getClient()

  const { data } = await client.query({
    query: gql`
      query GetLayout {
        generalSettings {
          title
          description
        }
        primaryMenuItems: menuItems(where: { location: PRIMARY }) {
          nodes {
            id
            label
            uri
          }
        }
        footerMenuItems: menuItems(where: { location: FOOTER }) {
          nodes {
            id
            label
            uri
          }
        }
      }
    `,
  })
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header menuItems={data.primaryMenuItems} />
        {children}
      </body>
    </html>
  )
}
